# Generated by Django 4.2.16 on 2024-11-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('script', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Share', 'Share'), ('MF', 'Mutual Fund')], max_length=10)),
                ('qty', models.PositiveIntegerField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=25)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pan', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('script', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('gf_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('short_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('long_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('short_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('long_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharesMF.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharesMF.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharesMF.usertable'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Share', 'Share'), ('MF', 'Mutual Fund')], max_length=10)),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharesMF.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharesMF.usertable')),
            ],
        ),
    ]
