# Generated by Django 4.2.16 on 2024-11-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0005_broker_purchase_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mode',
            field=models.CharField(blank=True, choices=[('secondary-market', 'Secondary Market'), ('new-issue', 'New Issue')], max_length=20, null=True),
        ),
    ]
