# Generated by Django 4.2.16 on 2024-11-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0006_purchase_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mehul',
            field=models.BooleanField(default=False),
        ),
    ]
