# Generated by Django 4.2.16 on 2024-11-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0007_purchase_mehul'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
