# Generated by Django 4.2.16 on 2024-11-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0009_stockprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
