# Generated by Django 4.2.16 on 2024-12-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0011_purchase_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='data_entry',
            field=models.BooleanField(default=False),
        ),
    ]
