# Generated by Django 4.2.16 on 2024-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0013_purchase_referenced_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=100)),
                ('split_date', models.DateField()),
                ('ratio', models.FloatField()),
            ],
        ),
    ]
