# Generated by Django 4.2.16 on 2024-12-05 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0014_stocksplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharesMF.purchase')),
            ],
        ),
    ]
