# Generated by Django 4.2.16 on 2024-12-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0015_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=100)),
                ('bonus_date', models.DateField()),
                ('ratio', models.FloatField()),
            ],
        ),
    ]
