# Generated by Django 4.2.16 on 2024-12-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0016_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_amount',
            new_name='_purchase_amount',
        ),
    ]
