# Generated by Django 4.2.16 on 2024-12-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0017_rename_purchase_amount_purchase__purchase_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='_purchase_amount',
            new_name='purchase_amount',
        ),
    ]
