# Generated by Django 4.2.16 on 2024-12-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0018_rename__purchase_amount_purchase_purchase_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('script', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('listing', models.BooleanField(default=False)),
            ],
        ),
    ]
