# Generated by Django 4.2.16 on 2024-12-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0019_primarymarketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptINE',
            fields=[
                ('script', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ine', models.CharField(max_length=50)),
            ],
        ),
    ]
