# Generated by Django 4.2.16 on 2025-01-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0020_scriptine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanId', models.AutoField(primary_key=True, serialize=False)),
                ('principleAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loanDate', models.DateField()),
                ('percentMonth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interestMonth', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Closed')], default=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_borrower', to='SharesMF.client')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_lender', to='SharesMF.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('site', models.CharField(max_length=255)),
                ('granter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_granter', to='SharesMF.client')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='SharesMF.loan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_recipient', to='SharesMF.client')),
            ],
        ),
    ]
