# Generated by Django 4.2.16 on 2025-01-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0021_client_loan_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField()),
                ('givenAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_payments', to='SharesMF.loan')),
            ],
        ),
    ]
