# Generated by Django 4.2.16 on 2025-01-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0022_principalpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principalpayment',
            name='id',
        ),
        migrations.AddField(
            model_name='principalpayment',
            name='prinID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
