# Generated by Django 4.2.16 on 2025-01-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0023_remove_principalpayment_id_principalpayment_prinid'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalpayment',
            name='prinInterestMonth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
