# Generated by Django 4.2.16 on 2025-01-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharesMF', '0024_principalpayment_prininterestmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
